#+TITLE: Cloq

Replicating a [[https://qlocktwo.com/][clock's]] design
([[https://clockforward.com/content/manuals/qlocktwo-classic.pdf][QLOCKTWO CLASSIC]])
with slight changes.

Made as an attempt to get familiar with ocaml's
[[https://github.com/leostera/minttea][minttea]] package.


** Screenshots

** Figuring out the time from the clock
Read the currently 'lit up' words to find a time.

Each of the four circles at the bottom represent a minute.
A filled white circle means we should add one minute to the time we figured out from the message displaye.

Number of seconds is not indicated.

** Installation
Dependency versions:
 - OCaml compiler v5.2.1
 - dune: v3.17
 - minttea: v0.0.2
 - spices: v0.0.2
 - ppx_string: v0.17.0

Doesn't work with OCaml compiler v5.3.0 because a minttea dependency needs <v5.2.2


OCaml compiler v5.2.1 can be installed with opam if it's not already installed:

#+begin_src bash
opam switch create 5.2.1
#+end_src

To build this project itself, first clone this repo and run the following
commands to install the dependencies:

#+begin_src bash
opam update
opam install minttea spices ppx_string dune
#+end_src

Then, build the project and run it:

#+begin_src bash
dune build
dune exec cloq
#+end_src 

Press Q to exit.

-----

#+begin_src 
*IT*​L​*IS*​ASAMPM
ACQUARTERDC
TWENTYFIVEX
HALFS​*TEN*​F​*TO*
PASTERUNINE
ONESIXTHREE
FOURFIVETWO
EIGHTELEVEN
*SEVEN*​TWELVE
TENSEOCLOCK
#+end_src






*IT*​L​*IS*​ASAMPM\\
ACQUARTERDC\\
TWENTYFIVEX\\
HALFS​*TEN*​F​*TO*\\
PASTERUNINE\\
ONESIXTHREE\\
FOURFIVETWO\\
EIGHTELEVEN\\
*SEVEN*​TWELVE\\
TENSEOCLOCK
